CREATE DATABASE  IF NOT EXISTS `sysnot` /*!40100 DEFAULT CHARACTER SET utf8 */;
USE `sysnot`;

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
DROP TABLE IF EXISTS `se_menu`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `se_menu` (
  `idmenu` int(11) NOT NULL,
  `titulo` varchar(30) NOT NULL,
  `nivel` int(11) NOT NULL,
  `idpadre` int(11) DEFAULT NULL,
  `rutaicono` varchar(50) DEFAULT NULL,
  `url` varchar(50) DEFAULT NULL,
  `orden` int(11) NOT NULL,
  `idaccion` int(11) DEFAULT NULL,
  PRIMARY KEY (`idmenu`),
  KEY `idpadre_idx` (`idpadre`)
);
/*!40101 SET character_set_client = @saved_cs_client */;

LOCK TABLES `se_menu` WRITE;
/*!40000 ALTER TABLE `se_menu` DISABLE KEYS */;
INSERT INTO `se_menu` VALUES (1,'Notaría',1,0,NULL,NULL,1,NULL),(2,'Catálogos',2,1,NULL,NULL,1,NULL),(3,'Tipos de Operaciones',3,2,NULL,NULL,1,NULL),(4,'Tipos de Trámites',3,2,NULL,NULL,3,NULL),(5,'Expedientes',2,1,NULL,NULL,2,3),(6,'Cotejos',2,1,NULL,NULL,3,NULL),(7,'Certificaciones',2,1,NULL,NULL,4,NULL),(8,'Seguridad',1,0,NULL,NULL,2,NULL),(9,'Usuarios',2,8,NULL,NULL,1,NULL),(10,'Roles',2,8,NULL,NULL,2,NULL),(11,'Sistema',1,0,NULL,NULL,3,NULL),(12,'Acciones',2,11,NULL,NULL,1,1),(13,'Opciones',2,11,NULL,NULL,2,NULL),(14,'Otro menu Notaría',2,1,NULL,NULL,5,NULL),(15,'Otro nivel Catálogos',3,2,NULL,NULL,2,NULL);
/*!40000 ALTER TABLE `se_menu` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

